### ISSUE TITLE
Jump to the official message in clicking the time field

### ISSUE THREAD

**Issue by tazu-yyy** [mazun/SlackStream#137]
![here](https://user-images.githubusercontent.com/2570904/30463550-4f19fc7e-9a07-11e7-868c-bbae97b251c3.PNG)

**Comment by soramichi** [comment]
The slack wrapper library we use does not support the `char.getPermalink` method. I will work on this issue after method is supported (there is actually a PR for this matter, so I suppose it will be supported soone https://github.com/slackapi/node-slack-sdk/pull/431)

**Comment by DominikPalo** [comment]
A new version of the slack wrapper library ([3.15.0](https://github.com/slackapi/node-slack-sdk/releases/tag/v3.15.0)) which supports the `chat.getPermalink` method was released yesterday :)

**Comment by soramichi** [comment]
@DominikPalo Hi, thank you very much for the information and your PR to the SDK!

**Comment by soramichi** [comment]
Implemented in #162.
